DEBUG      = FALSE
DIM        = 2
COMP	   = gnu
USE_MPI    = TRUE
USE_OMP    = FALSE
USE_CUDA   = FALSE

TINY_PROFILE = FALSE
PROFILE      = FALSE # TRUE overrides TINY_PROFILE


# define the location of the ml-reactions home directory
MLREACTIONS_HOME  := ../..

Bpack   := ./Make.package
Blocs   := .

include $(MLREACTIONS_HOME)/cpp/betadecay_makefile/Make.ml-betadecay
